pub(super) const PRIMARY_CONTENT_SURFACE_TOKENS: [&str; 8] = [
    "article", "body", "content", "entry", "guide", "help", "main", "text",
];
pub(super) const READER_CONTENT_HINT_TOKENS: [&str; 6] =
    ["article", "body", "content", "main", "story", "text"];
pub(super) const LAYOUT_SHELL_TOKENS: [&str; 7] = [
    "column",
    "columns",
    "container",
    "frame",
    "grid",
    "layout",
    "wrapper",
];
pub(super) const STRONG_UTILITY_CHROME_TOKENS: [&str; 34] = [
    "accessories",
    "affiliate",
    "buy",
    "carrier",
    "compare",
    "comparison",
    "deal",
    "deals",
    "disambiguation",
    "disclaimer",
    "disclosure",
    "environment",
    "faq",
    "hatnote",
    "incentive",
    "legal",
    "modal",
    "offer",
    "offers",
    "policy",
    "pricing",
    "promo",
    "report",
    "ribbon",
    "shop",
    "shopping",
    "specialist",
    "subjectpageheader",
    "tag",
    "tags",
    "terms",
    "trade",
    "upgrade",
    "values",
];
pub(super) const UTILITY_CHROME_TOKENS: [&str; 100] = [
    "ad",
    "advert",
    "affiliate",
    "appearance",
    "author",
    "audio",
    "bio",
    "breadcrumb",
    "buy",
    "byline",
    "categories",
    "category",
    "caption",
    "carrier",
    "catlinks",
    "comment",
    "comments",
    "compare",
    "comparison",
    "copied",
    "copy",
    "control",
    "controls",
    "count",
    "deal",
    "deals",
    "disambiguation",
    "disclaimer",
    "disclosure",
    "dropdown",
    "environment",
    "eyebrow",
    "edit",
    "editsection",
    "featured",
    "export",
    "faq",
    "filter",
    "filters",
    "globalnav",
    "hatnote",
    "hidden",
    "indicator",
    "indicators",
    "incentive",
    "interface",
    "kicker",
    "lang",
    "language",
    "legal",
    "localnav",
    "meta",
    "metadata",
    "media",
    "menu",
    "modal",
    "nav",
    "newsletter",
    "noprint",
    "offer",
    "offers",
    "pending",
    "pagination",
    "player",
    "policy",
    "portlet",
    "pricing",
    "print",
    "promo",
    "report",
    "reaction",
    "reactions",
    "recommend",
    "recommended",
    "related",
    "revision",
    "ribbon",
    "share",
    "shop",
    "shopping",
    "sidebar",
    "social",
    "specialist",
    "status",
    "subtitle",
    "subscribe",
    "subjectpageheader",
    "tag",
    "tags",
    "feedback",
    "terms",
    "topic",
    "topics",
    "trade",
    "upsell",
    "upgrade",
    "utility",
    "values",
    "video",
    "widget",
];
pub(super) const UI_ROLES: [&str; 8] = [
    "complementary",
    "dialog",
    "menu",
    "menubar",
    "navigation",
    "search",
    "tablist",
    "toolbar",
];
pub(super) const READER_AUXILIARY_TOKENS: [&str; 20] = [
    "backlink",
    "bibliography",
    "citation",
    "citations",
    "cite",
    "disambiguation",
    "editsection",
    "footnote",
    "footnotes",
    "hatnote",
    "noteref",
    "reflist",
    "reference",
    "references",
    "redirect",
    "shortdescription",
    "subjectbar",
    "subjectpageheader",
    "sister",
    "toc",
];
pub(super) const READER_NOTICE_TOKENS: [&str; 14] = [
    "advertising",
    "affiliate",
    "commission",
    "copyright",
    "cookie",
    "cookies",
    "disclosure",
    "earn",
    "links",
    "policy",
    "privacy",
    "purchase",
    "sponsored",
    "terms",
];
pub(super) const READER_NOTICE_PHRASES: [&str; 8] = [
    "affiliate commission",
    "fair use",
    "here's how it works",
    "how it works",
    "terms apply",
    "we may earn",
    "when you purchase through links",
    "when you purchase through links on our site",
];
pub(super) const READER_NOTICE_STRONG_PHRASES: [&str; 4] = [
    "copyright act",
    "reviewed by an editor",
    "this article was generated",
    "used for the purpose of news reporting",
];
pub(super) const AUXILIARY_SECTION_HEADINGS: [&str; 7] = [
    "citations",
    "external links",
    "further reading",
    "notes",
    "other sources",
    "references",
    "see also",
];
pub(super) const SOURCE_ATTRIBUTION_PREFIXES: [&str; 3] = ["source:", "sources:", "via:"];
pub(super) const NOTE_FRAGMENT_PREFIXES: [&str; 8] = [
    "#bib",
    "#cite",
    "#fn",
    "#footnote",
    "#note",
    "#ref",
    "#refs",
    "#r",
];
