use super::*;

#[test]
fn local_mutation_campaign_executes_a_disposable_workspace_and_reconciles_its_results() {
    let repository = tempdir().expect("temporary workspace");
    fs::write(
        repository.path().join("Cargo.toml"),
        "[workspace]\nmembers = [\"crates/example\"]\nresolver = \"3\"\n",
    )
    .expect("write workspace manifest");
    fs::write(
        repository.path().join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"mutation-fixture\"\nversion = \"0.1.0\"\n",
    )
    .expect("write locked workspace inventory");
    let crate_root = repository.path().join("crates/example");
    fs::create_dir_all(crate_root.join("src")).expect("create crate source directory");
    fs::write(
        crate_root.join("Cargo.toml"),
        "[package]\nname = \"mutation-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("write crate manifest");
    fs::write(
        crate_root.join("src/lib.rs"),
        "pub fn classify(value: i32) -> i32 {\n    if value > 0 { value + 1 } else { value - 1 }\n}\n\n#[cfg(test)]\nmod tests {\n    use super::classify;\n\n    #[test]\n    fn classifies_each_sign() {\n        assert_eq!(classify(2), 3);\n        assert_eq!(classify(0), -1);\n    }\n}\n",
    )
    .expect("write fixture source");

    let output = repository.path().join("mutation-output");
    let summary = crate::mutants::run_local_mutation_campaign_for_gate(
        repository.path(),
        &output,
        None,
        None,
    )
    .expect("run disposable local mutation campaign");

    assert!(summary.total_mutants > 0);
    assert_eq!(
        summary.total_mutants,
        summary.caught + summary.missed + summary.timed_out + summary.unviable
    );
    let canonical = output.join("mutants.out");
    assert!(canonical.join("outcomes.json").is_file());
    assert!(canonical.join("local-aggregate.json").is_file());
    assert!(!output.join("local-shard-runs").exists());
}
