[package]
name = "htmlcut-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
autolib = false
publish = false

[[bin]]
name = "htmlcut"
path = "src/main.rs"

[dependencies]
clap.workspace = true
htmlcut-core.workspace = true
tempfile.workspace = true
tar.workspace = true
os_pipe.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[dev-dependencies]
htmlcut-tempdir.workspace = true

[lints]
workspace = true
