use super::candidates::{build::*, promotion::*, scoring::*};
use super::samples::*;
use super::selectors::*;
use super::text::*;
use super::*;
use crate::document::{parse_document_node, select_first};
use std::collections::BTreeSet;

mod candidate_bias;
mod candidate_limits;
mod extraction_bias;
mod false_guard_paths;
mod helper_edges;
mod inspection_basics;
mod precise_descendants;
mod promotion_guards;
mod promotion_thresholds;
mod reading_promotion;
mod scoring;
mod selector_and_sampling;
mod support;
